# Use the official MySQL 8.4 image as the base image
FROM mysql:8.4



# Expose the default MySQL port (optional, as Docker Compose will handle this)
EXPOSE 3306

# Set the working directory (optional, MySQL doesn't require this)
WORKDIR /var/lib/mysql

# Start the MySQL server
CMD ["mysqld"]